version: '3.8'
services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - '8080:8080'
  db:
    env_file: .env
    image: 'postgres:15.2'
    container_name: springboot3-example_db_1
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres-data: