
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot3-example-deployment
  labels:
    app: springboot3-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot3-example
  template:
    metadata:
      labels:
        app: springboot3-example
    spec:
      containers:
        - name: springboot3-example-app
          image: registry.gitlab.com/$TAG_COMMIT
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: SPRING_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pass
                  key: postgresql-user-password
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name:  postgresql-config-map
                  key: postgresql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name:  postgresql-config-map
                  key: postgresql-database-name
            - name: SPRING_POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config-map
                  key: postgresql-user-username
            - name: SPRING_POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: springboot-config-map
                  key: db-url
      imagePullSecrets:
        - name: registry.gitlab.com
---
apiVersion: v1
kind: Service
metadata:
  name: springboot3-example-service
  labels:
    app: springboot3-example
spec:
  type: LoadBalancer
  selector:
    app: springboot3-example
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000