
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot3-example_app
  labels:
    app: springboot3-example_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot3-example_app
  template:
    metadata:
      labels:
        app: springboot3-example_app
    spec:
      containers:
        - name: springboot3-example_app
          image: registry.gitlab.com/$TAG_COMMIT
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pass
                  key: postgresql-user-password
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name:  postgresql-config-map
                  key: postgresql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name:  postgresql-config-map
                  key: postgresql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config-map
                  key: postgresql-user-username
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: springboot3-example_app
  labels:
    app: springboot3-example_app
spec:
  type: LoadBalancer
  selector:
    app: springboot3-example_app
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000